name: CI

on:
  push:
    branches:
      - master

jobs:
  runs-on: ubuntu-latest
    name: Builds bookstore backend
    using: 'docker'
    image: 'Dockerfile'
    steps:
      - run: docker build -t bernardkllogjri/bookstore