name: CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Docker Action
    uses: zenato/docker-action@v1.0.0
    with:
      username: { { secrets.DOCKER_USER } }
      password: { { secrets.DOCKER_USER } }
      repository: { { secrets.DOCKER_REPO } }
      tag: { { $GITHUB_SHA } }
    steps:
      - name: Build
      - run: docker build -t .
